import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const html = fs.readFileSync(path.join(root, "panel", "index.html"), "utf8");
if (!html.includes('/src/panel/main.tsx')) throw new Error("panel entrypoint missing");
const mainTsx = fs.readFileSync(path.join(root, "src", "panel", "main.tsx"), "utf8");
if (!mainTsx.includes('if (record.tool === "batch_call" && children.length > 0) toggle(record); else setSelected(record);')) throw new Error("batch_call rows must expand instead of opening details");
if (!mainTsx.includes('function formatDuration(ms: number): string')) throw new Error("duration formatter missing");
if (!mainTsx.includes('function buildLaunchCommand(cfg: Record<string, any>): string')) throw new Error("launch command generator missing");
if (!mainTsx.includes('Copy launch command')) throw new Error("launch command copy action missing");
if (mainTsx.includes('StatusLine label="����·��"') || mainTsx.includes('StatusLine label="MCP Tunnel"')) throw new Error("sidebar tunnel status card must be removed");
if (mainTsx.includes('tool ��ִ����...')) throw new Error("MCP audit detail must not contain mojibake text");
if (!mainTsx.includes('<Loading text="tool 执行中..." />')) throw new Error("active MCP audit detail loading text missing");
if (!mainTsx.includes('if (value < 1000) return `${value.toFixed(1)} ms`;')) throw new Error("duration formatter must use milliseconds for sub-second values");
if (!mainTsx.includes('if (value < 60_000) return `${(value / 1000).toFixed(2)} s`;')) throw new Error("duration formatter must use seconds");
if (fs.existsSync(path.join(root, "widgets"))) throw new Error("widgets directory must be removed");
if (fs.existsSync(path.join(root, "src", "widgets"))) throw new Error("src/widgets directory must be removed");
if (fs.existsSync(path.join(root, "src", "widget-ui"))) throw new Error("widget-ui directory must be removed");
console.log("frontend contract smoke: panel entrypoint only");
